# Generated by Django 4.1.1 on 2022-09-22 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'XRPL аккаунт',
                'verbose_name_plural': 'XRPL аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=256, unique=True)),
                ('ledger_index', models.PositiveBigIntegerField()),
                ('amount', models.CharField(max_length=80)),
                ('account', models.CharField(max_length=256)),
                ('destinationTag', models.PositiveBigIntegerField(blank=True, null=True)),
                ('fee', models.PositiveIntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='service.accountaddress')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.AddIndex(
            model_name='transactions',
            index=models.Index(fields=['ledger_index'], name='service_tra_ledger__6014f4_idx'),
        ),
        migrations.AddIndex(
            model_name='transactions',
            index=models.Index(fields=['destination', 'account'], name='service_tra_destina_41a5f2_idx'),
        ),
    ]
